name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build and push Docker image for app
      run: |
        docker build -t ghcr.io/jesusvillegas0/k8s-deployment-practice:latest -f app/Dockerfile .
        docker push ghcr.io/jesusvillegas0/k8s-deployment-practice:latest

    - name: Build and push Docker image for db
      run: |
        docker build -t ghcr.io/jesusvillegas0/k8s-deployment-practice-db:latest -f db/Dockerfile .
        docker push ghcr.io/jesusvillegas0/k8s-deployment-practice-db:latest
